"""Phase 2 SRS §7 item 1: clean sample, T_gt = identity -> both baselines
recover it tightly. Uses data/S1/rot0.0_trans0_noise1_none/seed0 — already
generated by the frozen grid, no new data needed."""
import numpy as np

from datagen.groundtruth import read_ground_truth
from datagen.io import read_cloud_ply, read_mesh_ply
from registration.api import register
from registration.params import load_params

SAMPLE_DIR = "data/S1/rot0.0_trans0_noise1_none/seed0"


def _load_sample():
    points, normals = read_cloud_ply(SAMPLE_DIR + "/cloud.ply")
    mesh = read_mesh_ply(SAMPLE_DIR + "/scene_mesh.ply")
    gt = read_ground_truth(SAMPLE_DIR + "/ground_truth.json")
    return (points, normals), mesh, np.array(gt["T_gt"])


def test_baseline_a_recovers_identity_within_bounds():
    cloud, mesh, T_gt = _load_sample()
    params = {**load_params("configs/registration_params.yaml"), "T_gt": T_gt}
    T_est, metrics = register(cloud, mesh, "A", params)
    assert metrics["status"] == "ok", metrics.get("failure")
    assert metrics["error_vs_gt"]["rot_deg"] < 0.05
    assert metrics["error_vs_gt"]["trans_mm"] < 1.0


def test_baseline_b_recovers_identity_within_bounds():
    cloud, mesh, T_gt = _load_sample()
    params = {**load_params("configs/registration_params.yaml"), "T_gt": T_gt}
    T_est, metrics = register(cloud, mesh, "B", params)
    assert metrics["status"] == "ok", metrics.get("failure")
    assert metrics["error_vs_gt"]["rot_deg"] < 0.05
    assert metrics["error_vs_gt"]["trans_mm"] < 1.0
